### ISSUE TITLE
Ambiguous post request error when not signed in 

### ISSUE THREAD

**Issue by kcmannem** [cloudfoundry/bosh-cli#318] opened 2017-09-19 14:11 UTC
Using command
`bosh2 -e d -d cf-7c7808dfb121358944da ssh diego_cell/0`
resulted in 
```
Using environment 'xx.xx.xx.xx' as anonymous user

Using deployment 'cf-7c7808dfb121358944da'

Setting up SSH in deployment 'cf-7c7808dfb121358944da':
  Performing request POST 'https://xx.xx.xx.xx:25555/deployments/cf-7c7808dfb121358944da/ssh':
    Performing POST request:
      Retry: Post https://xx.xx.xx.xx:25555/deployments/cf-7c7808dfb121358944da/ssh: http: ContentLength=560 with Body length 0

Exit code 1
```

Recommended Error Message: 'User is not logged in'.

**Comment by dpb587-pivotal** [comment] 2017-09-19 22:36
Duplicate of #91

**Closed by dpb587-pivotal** 2017-09-19 22:36 UTC
