### ISSUE TITLE
Strange syntax for bosh tasks --recent

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry/bosh-cli#413] opened 2018-04-09 16:25 UTC
Hi.
I thinks `bash tasks` has a bit unusual syntax for options. I mean different from unix way and different from other options.
1)  `bosh tasks --recent=4` - okay
2) 
```
$ bosh tasks -r 4
Command '*cmd.TasksOpts' does not support extra arguments: 4
Exit code 1
```
why? we can use `-e` or `-d` without `=` in bosh cli .

3) `bosh tasks -r=4` - this is just alien :-)

I understand that this is not a big deal, but still bothers me :-)
Thanks.

P.S.
```
bosh -v
version 3.0.1-712bfd7-2018-03-13T23:26:43Z
```

**Comment by dpb587-pivotal** [comment] 2018-04-09 16:48
Agreed it's unusual and odd UX, but closing as a duplicate of https://github.com/cloudfoundry/bosh-cli/issues/225. Feel free to +1 on there, or leave an additional comment.

**Closed by dpb587-pivotal** 2018-04-09 16:48 UTC
