### ISSUE TITLE
No diff for cloud-config, cpi-config, runtime-config

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#162] opened 2017-03-08 07:49 UTC
It is really painful to do the diff on your own, bosh should do this for me. It is already doing it for manifests, so I guess the same logic should be applied to all other .yml files I upload.

This avoids mistakes, as all of those configs cannot be rolled back easily.

**Comment by tjvman** [comment] 2017-03-09 21:38
This is a duplicate of #7.

**Closed by tjvman** 2017-03-09 21:38 UTC
