### ISSUE TITLE
`deploy --dry-run` should handle locks more gracefully

### ISSUE THREAD

**Issue by anEXPer** [cloudfoundry/bosh-cli#112] opened 2017-02-01 23:31 UTC
When we run `bosh deploy -n --dry-run ../cf-deployment/cf-deployment.yml` while targeted to an env with `cf-deployment` already deployed, and there is a deploy lock on that deployment, we get this:

```
Task 438

23:17:13 | Error: PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block


Started  Wed Feb  1 23:17:13 UTC 2017
Finished Wed Feb  1 23:17:13 UTC 2017
Duration 00:00:00

Task 438 error

Updating deployment:
  Expected task '438' to succeed but was state is 'error'

Exit code 1
```

Here's some relevant-seeming output from the debug:

```
I, [2017-02-01 23:17:42 #16967] [task:439]  INFO -- DirectorJobRunner: Acquiring deployment lock on cf
D, [2017-02-01 23:17:42 #16967] [task:439] DEBUG -- DirectorJobRunner: Acquiring lock: lock:deployment:cf
D, [2017-02-01 23:17:42 #16967] [task:439] DEBUG -- DirectorJobRunner: (0.000472s) SELECT count(*) AS "count" FROM "locks" WHERE (("name" = 'lock:deployment:cf') AND ("uid" = '4e081e23-d271-49df-b4a3-11046d5dfd7b')) LIMIT 1
E, [2017-02-01 23:17:42 #16967] [task:439] ERROR -- DirectorJobRunner: PG::Error: ERROR:  duplicate key value violates unique constraint "locks_name_key"
DETAIL:  Key (name)=(lock:deployment:cf) already exists.: INSERT INTO "locks" ("name", "uid", "expired_at") VALUES ('lock:deployment:cf', '4e081e23-d271-49df-b4a3-11046d5dfd7b', '2017-02-01 23:17:53.754112+0000') RETURNING *
E, [2017-02-01 23:17:42 #16967] [task:439] ERROR -- DirectorJobRunner: PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block: UPDATE "locks" SET "uid" = '4e081e23-d271-49df-b4a3-11046d5dfd7b', "expired_at" = '2017-02-01 23:17:53.754112+0000' WHERE (("name" = 'lock:deployment:cf') AND ("expired_at" < '2017-02-01 23:17:42.759097+0000'))
D, [2017-02-01 23:17:42 #16967] [task:439] DEBUG -- DirectorJobRunner: (0.000092s) ROLLBACK
E, [2017-02-01 23:17:42 #16967] [task:439] ERROR -- DirectorJobRunner: PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

So, it looks like the deployment lock is preventing the dry run. Which... doesn't seem right. And if it was right, it probably shouldn't fail out with an obscure database error.

**Comment by Niranjana-5588** [comment] 2017-07-14 18:40
Hi, any update on this

I got the same issue with `bosh deploy`

The output on terminal is

```
Director task 11
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started compiling packages
  Started compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc
  Started compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > nginx/e77a07866c05979b49389fe36d66846411ba08a2
  Started compiling packages > ruby-2.3/3a224c0fb813a20b92de640ac779e1754a2748b4
  Started compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d

Task 11 error

For a more detailed error report, run: bosh task 11 --debug

```
Looking at the log data by running command `bosh task 11 --debug`

```
D, [2017-07-14 18:17:58 #7225] [task:11] DEBUG -- DirectorJobRunner: (0.000084s) BEGIN
E, [2017-07-14 18:17:58 #7225] [task:11] ERROR -- DirectorJobRunner: PG::Error: ERROR:  duplicate key value violates unique constraint "locks_name_key"
DETAIL:  Key (name)=(lock:deployment:cf-warden) already exists.: INSERT INTO "locks" ("name", "uid", "expired_at") VALUES ('lock:deployment:cf-warden', 'a7090fc1-b733-421c-8d8b-ca702e152867', '2017-07-14 18:18:09.993627+0000') RETURNING *
D, [2017-07-14 18:17:58 #7225] [task:11] DEBUG -- DirectorJobRunner: (0.000087s) ROLLBACK
```

**Comment by tjvman** [comment] 2017-10-03 21:19
@anEXPer @Niranjana-5588 The transaction error shouldn't occur when running against version 263.1+ of Bosh.

**Comment by jfmyers9** [comment] 2018-09-25 21:02
At this point, the `deploy --dry-run` still needs to grab the deployment lock, so this is intended behavior.

As far as the original issue, that error now fails for the usual deployment lock error that exists for many `bosh` commands.

Going to close this issue. Please feel free to create a new issue if you have further questions.

**Closed by jfmyers9** 2018-09-25 21:02 UTC
Labels: triaged
