### ISSUE TITLE
Please provide downloadable binaries for cli v2 on the release page

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#95] opened 2017-01-12 01:09 UTC
Thank you

**Comment by tjvman** [comment] 2017-01-12 01:11
Closing, this is a duplicate of https://github.com/cloudfoundry/bosh-cli/issues/25

**Closed by tjvman** 2017-01-12 01:11 UTC

**Comment by cppforlife** [comment] 2017-01-12 02:17
@shalako Updated https://bosh.io/docs/cli-v2.html#install to show direct links.

**Comment by shalako** [comment] 2017-01-12 18:16
Thank you
