### ISSUE TITLE
error thrown on exiting ssh session

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#132] opened 2017-02-11 03:33 UTC
```
router/388cc459-fcbe-4538-b82b-d37a3bee0ed9:~$ exit
logout
Connection to 10.0.16.5 closed.
Killed by signal 1.

Running SSH:
  1 error(s) occurred:

* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/shannon/.bosh/tmp/ssh-priv-key685444168 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/shannon/.bosh/tmp/ssh-known-hosts754332423 -o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l vcap 35.184.49.153 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 10.0.16.5 -l bosh_ed49601128e04526', stdout: '', stderr: '': exit status 130

Exit code 1
```

```
$ gosh --version
version 0.0.147-ba602d1-2017-01-11T20:05:06Z

Succeeded
```

**Comment by tjvman** [comment] 2017-02-14 02:50
This is a duplicate of https://github.com/cloudfoundry/bosh-cli/issues/41. Closing.

**Closed by tjvman** 2017-02-14 02:50 UTC
