### ISSUE TITLE
`bosh create-release` should warn you for ruby cli based releases 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#173] opened 2017-03-15 08:57 UTC
When creating a release with the go cli on a repo which has releases previously created with the ruby cli, the cli doesn't complain but just creates a release which doesn't contain any blobs. You have to execute `bosh reset-release` to prepare the bosh release for the new go  cli. It will be more helpful if the cli warns you or fails in this case.

**Comment by dpb587-pivotal** [comment] 2017-03-18 00:04
Closing - duplicate of #145

**Closed by dpb587-pivotal** 2017-03-18 00:04 UTC
