### ISSUE TITLE
sha mismatch message is not very clear

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/bosh-cli#205] opened 2017-04-20 19:33 UTC
# Issue
When there's a sha mismatch I get a message about digests and streams. This could be confusing to a user new to bosh or not fully comfortable with the terminology (or english in general).

```
Started validating
  Downloading release 'concourse'... Failed (00:01:26)
Failed validating (00:01:26)

Failed to download from 'https://bosh.io/d/github.com/concourse/concourse?v=2.7.3':
  Verifying digest for downloaded file:
    Expected stream to have digest 'af9424c8f9d9ea14e961743e4d8d4fa187fc1e31' but was 'ca38944353c893660a428cc6678941734b51b036'

Exit code 1
```

# Proposed Solution
change message:

```diff
Started validating
  Downloading release 'concourse'... Failed (00:01:26)
Failed validating (00:01:26)

Failed to download from 'https://bosh.io/d/github.com/concourse/concourse?v=2.7.3':
  Verifying digest for downloaded file:
-    Expected stream to have digest 'af9424c8f9d9ea14e961743e4d8d4fa187fc1e31' but was 'ca38944353c893660a428cc6678941734b51b036'
+    Expected remote release to have sha1 'af9424c8f9d9ea14e961743e4d8d4fa187fc1e31' but was 'ca38944353c893660a428cc6678941734b51b036'

Exit code 1
```

**Comment by freddesbiens** [comment] 2018-10-01 14:37
Validated that this is still an issue. Closing and reopening this story so that gitbot will create a corresponding tracker story.

**Comment by h4xnoodle** [comment] 2019-01-09 21:16
Hello @zaksoup thanks for bringing this to our attention. 

At this time, this is intended behaviour. There are many other terms within the Bosh ecosystem that may be advanced for users beginning with software deployment or verification. We will continue to use terms that users can then research and find the canonical definition/explanation. We generally expect those who are deploying software with Bosh to have some knowledge of common principles.

Thanks,
Rebecca @h4xnoodle, Bosh, Pivotal

**Closed by h4xnoodle** 2019-01-09 21:16 UTC
Labels: triaged, unscheduled

**Comment by dpb587-pivotal** [comment] 2019-01-09 21:45
[@zaaaaaaaaksoup](https://github.com/zaksoup)... I remember when you were on the BOSH team!
