### ISSUE TITLE
Delete environment causes orphaned VMs

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry/bosh-cli#216] opened 2017-05-09 07:56 UTC
Without deleting the deployments of a BOSH director, we deleted the director by using `delete env`.
This process was successful but left all its deployments running.
We manually had to delete all VMs from the IaaS panel which caused a lot of issues.

Is this behaviour expected? I would expect a warning/error when there are still deployments running.

**Comment by cppforlife** [comment] 2017-05-11 21:58
@amuessig currently create-env/delete-env commands are completely oblivious to what they are deploying/deleting. they are just managing a single generic vm with some configuration on it. (we also use create-env for example to manage a jumpbox machine). additionally having delete-env do clean up and deletion of deployments sounds pretty dangerous. i dont think we should implement such feature.

**Comment by dpb587-pivotal** [comment] 2017-06-30 21:57
Closing since this is currently expected behavior. Be sure to run `bosh delete-deployment` and `bosh clean-up --all` if you are using `delete-env` to truly tear down an entire director environment.

**Closed by dpb587-pivotal** 2017-06-30 21:57 UTC
Labels: discuss
