### ISSUE TITLE
Is a internal ca certificate can be used for 

### ISSUE THREAD

**Issue by spkrsna** [cloudfoundry/bosh-cli#624] opened 2023-07-28 10:32 UTC
Hi, 

Instead of using bosh generated self signed certificates , is a company generated internal "ca's" and certificates can be used
in creds.yml  under respective certificates like  default_ca , uaa_ssl , director_ca etc

The purpose is we are unable to track expiring certs , if we are using our tool generated certificates we can easily monitor the expiring dates and take action easily.

Is the above can be done or it won't work?

Thanks!

**Comment by mvach** [comment] 2023-07-28 12:17
Should be a duplicate of [#2459](https://github.com/cloudfoundry/bosh/issues/2459)

**Comment by spkrsna** [comment] 2023-07-31 07:19
Thanks @mvach  for the answers , i will check on that repo too.

**Closed** 2023-07-31 08:38 UTC
