### ISSUE TITLE
When interpolating an ops-file with a missing path, I'd like to know which ops-file failed

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#142] opened 2017-02-21 19:01 UTC
If I use an ops-file like:

```
- type: replace
  path: /my/name=key/does/name=not/exist
  value: "hello"
```

but the path does not resolve, I get a message like:

```
Evaluating manifest:
  Expected to find a map key 'exist' for path '/my/name=key/does/name=not/exist' (found map keys: 'name')

Exit code 1
```

If I have a lot of ops-files, it might be hard for me to find the offender. I'd like to know which ops-file was getting parsed at the time of the error (and even better, which ~~link~~line the operation was defined on)

**Comment by cppforlife** [comment] 2017-02-21 20:36
which line you mean?

**Comment by wendorf** [comment] 2017-02-21 23:05
Yep, sorry. Typo.

**Comment by jfmyers9** [comment] 2018-09-25 21:11
Closing this as it is a duplicate of https://github.com/cloudfoundry/bosh-cli/issues/68

**Closed by jfmyers9** 2018-09-25 21:11 UTC
Labels: triaged
