### ISSUE TITLE
SSL Certficates are generate incorrectly with large duration/expiry

### ISSUE THREAD

**Issue by wildloop** [cloudfoundry/bosh-cli#540] opened 2019-08-31 08:12 UTC
Due to bug: https://www.pivotaltracker.com/n/projects/956238/stories/168066776
fixed: https://github.com/cloudfoundry/config-server/commit/c9ac3617cb97ade27d27a2527f9695e2e0f7a4f2#diff-522e1607e2a1cf9b59079a10760c6b99
Now max working duration is: 1365 (max int16/24).

**Comment by h4xnoodle** [comment] 2019-09-03 14:47
I'm assuming this is essentially a duplicate of the bug I filed and then fixed. Closing this. Thanks for pointing it out as well :)

**Closed by h4xnoodle** 2019-09-03 14:47 UTC
Labels: unscheduled
