### ISSUE TITLE
`bosh create-release` does not use latest blobs, only the ones in the `blobs` cache directory

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-cli#99] opened 2017-01-16 19:47 UTC
Reproducible steps:

```
git clone https://github.com/cloudfoundry/loggregator
cd loggregator
git checkout v74.0.1
bosh create-release
git checkout v74.0.2
bosh create-release
#notice the output, nothing about downloading blobs
rm -Rf blobs/
bosh create-release
vimdiff dev_releases/loggregator/*.yml
```

![screenshot from 2017-01-16 12 02 13](https://cloud.githubusercontent.com/assets/75184/21996967/ef3003ca-dbe9-11e6-8cde-2050fa461c04.png)

**Comment by wfernandes** [comment] 2017-01-19 22:36
This doesn't work even if you explicitly call `bosh sync-blobs` before `bosh create-release`.

**Comment by cppforlife** [comment] 2017-01-19 22:48
for now you have to rm -rf blobs/ before running bosh create-release.

**Comment by beyhan** [comment] 2017-05-05 14:52
This seems to be related to #145. It will be great to have better error when switching from bosh cli v1 to bosh cli v2.

**Comment by dpb587-pivotal** [comment] 2017-05-19 23:54
Closing - duplicate of #145. As mentioned, a workaround is `bosh reset-release`.

**Closed by dpb587-pivotal** 2017-05-19 23:54 UTC
Labels: planned-enhancement, problem
