### ISSUE TITLE
bosh cli removes leading zeros when interpolating variables

### ISSUE THREAD

**Issue by cdutra** [cloudfoundry/bosh-cli#218] opened 2017-05-09 18:08 UTC
bosh cli version 2.0.16 removes leading zeros from version when interpolating variables.

Sample manifest:
```
...
stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell_version))
...
```

`bosh interpolate -v stemcell_version="3363.20" manifest.yml` outputs:
```
...
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3363.2
...
```

**Comment by dpb587-pivotal** [comment] 2017-05-09 18:25
Duplicate of #208

Workaround is to pass the value as YAML to force it as a string: `-v stemcell_version='"3363.20"'`

Also, `s/leading/trailing/g` :)

**Closed by dpb587-pivotal** 2017-05-09 18:25 UTC
